# Generated by Django 2.1.5 on 2019-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_envio', models.IntegerField()),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta1', models.CharField(max_length=100, verbose_name='1ª alternativa')),
                ('resposta2', models.CharField(max_length=100, verbose_name='2ª alternativa')),
                ('resposta3', models.CharField(blank=True, max_length=100, null=True, verbose_name='3ª alternativa')),
                ('resposta4', models.CharField(blank=True, max_length=100, null=True, verbose_name='4ª alternativa')),
                ('imagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagem (url)')),
            ],
            options={
                'verbose_name': 'Pesquisa Leme',
                'verbose_name_plural': 'Pesquisas',
            },
        ),
    ]
